# Generated by Django 4.0.6 on 2022-07-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateOfCreate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AddField(
            model_name='product',
            name='numbers',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/category', verbose_name='تصویر دسته بندی'),
        ),
    ]
