# Generated by Django 4.0.6 on 2022-07-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_product_dateofcreate_product_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='عنوان دسته بندی'),
        ),
    ]
