# Generated by Django 4.0.6 on 2022-07-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='siteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('siteUrl', models.CharField(max_length=200, verbose_name='دامنه سایت')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس سایت')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن سایت')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس سایت')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='ایمیل سایت')),
                ('copyRight', models.CharField(max_length=200, verbose_name='متن کپی رایت سایت')),
                ('siteLogo', models.ImageField(upload_to='images/siteSetting', verbose_name='لوگو سایت')),
                ('aboutUs', models.TextField(verbose_name='درباره ما')),
                ('isMainSettings', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنطیمات',
            },
        ),
    ]
