# Generated by Django 4.0.6 on 2022-07-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='footerLinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی آدرس ها در فوتر',
                'verbose_name_plural': 'دسته بندی های آدرس ها در فوتر',
            },
        ),
        migrations.CreateModel(
            name='footerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('footerLinkRelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.footerlinkbox', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'آدرس در فوتر',
                'verbose_name_plural': 'آدرس ها در فوتر',
            },
        ),
    ]
